version: "3.8"

services:
  dbupdate:
    image: "maxmindinc/geoipupdate"
    env_file:
      - stack.env
    volumes:
      - db-volume:/usr/share/GeoIP
  backend:
    build: ./api
    restart: on-failure:10
    depends_on:
      - dbupdate
    env_file:
      - stack.env
    volumes:
      - db-volume:/usr/src/app
    ports:
      - 8080:3000

volumes:
  db-volume:
